### ISSUE TITLE
Could you please add support for batch converting option?

### ISSUE THREAD

**Issue by YangJianchong** [biodranik/HEIF#3]

**Comment by biodranik** [comment]
Why do you need it and how do you see it? Just to pass an indefinite list of files on the command line? Or to pass a file which contains paths/names of files to be processed?

For now, you can easily process as many files as you want just by calling it from bash or even command line like that:
```bash
for file in path/to/files/*.jpg; do
  ./HEIF -q=1.0 "$file"
done
```
Or one line: ```for file in path/to/files/*.jpg; do ./HEIF -q=1.0 "$file"; done
```

**Comment by YangJianchong** [comment]
> Why do you need it and how do you see it? Just to pass an indefinite list of files on the command line? Or to pass a file which contains paths/names of files to be processed?
> 
> For now, you can easily process as many files as you want just by calling it from bash or even command line like that:
> 
> ```shell
> for file in path/to/files/*.jpg; do
>   ./HEIF -q=1.0 "$file"
> done
> ```
> 
> Or one line: `for file in path/to/files/*.jpg; do ./HEIF -q=1.0 "$file"; done`

Thank you so much!
