### ISSUE TITLE
Image size changed

### ISSUE THREAD

**Issue by CarlosJimenez** [biodranik/HEIF#4]
When I convert a image from png to heic the image height is reduced in one pixel
Using Imagemagick

$identify  example.png
example.png PNG 1125x2436 1125x2436+0+0 8-bit sRGB 2.89787MiB 0.000u 0:00.004

$heif example.png

$identify example.heic 
example.heic HEIC 1124x2436 1124x2436+0+0 8-bit YCbCr 0.000u 0:00.001

[example.png.zip](https://github.com/biodranik/HEIF/files/3289571/example.png.zip)

**Comment by biodranik** [comment]
Thanks for reporting it. Unfortunately, it looks like an internal codec issue, and I don't know how to fix it.

**Comment by CarlosJimenez** [comment]
Thank a lot
